# Generated by Django 2.2.5 on 2019-09-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('web_data_title', models.TextField()),
                ('web_identifier', models.TextField(max_length=5, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_website',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
                ('web_identifier', models.TextField(max_length=5)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Website')),
            ],
            options={
                'db_table': 'tb_link',
            },
        ),
    ]
