# Generated by Django 2.2.5 on 2019-09-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='link',
            table='Link',
        ),
        migrations.AlterModelTable(
            name='website',
            table='Website',
        ),
    ]
