# Generated by Django 2.2.5 on 2019-09-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190926_0000'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='link',
            table='tb_link',
        ),
        migrations.AlterModelTable(
            name='website',
            table='tb_website',
        ),
    ]
