# Generated by Django 2.2.5 on 2019-09-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190926_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.TextField(default=None),
        ),
    ]
