# Generated by Django 2.2.5 on 2019-09-26 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190926_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
