# Generated by Django 2.2.5 on 2019-09-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190926_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.TextField(unique=True),
        ),
    ]
